### Postprocessing of data extracted by the Sniffer.

### TODO: add data types and physiological bounds to schema (and 'normal bounds'?). Add derived variables and forumlae? Add unit conversion functions?

In [21]:
import sqlite3
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
%matplotlib_inline

os.chdir('../streamlit/')
from utilities import LocalDatabaseWrapper
os.chdir('../development')

UsageError: Line magic function `%matplotlib_inline` not found.

In [34]:
project_name = "smartt_bmj_open_plus"
database_path = Path("../data")

In [35]:
local_db = LocalDatabaseWrapper(
            database_path / f"{project_name}.db"
        )

In [40]:
local_db.query_pd(
    "select * from sqlite_master where type = 'table';"
    
)

,type,name,tbl_name,rootpage,sql
0,table,schema,schema,2,"CREATE TABLE ""schema"" (\n""mapping_complete"" IN..."
1,table,info,info,5,"CREATE TABLE ""info"" (\n""name"" TEXT,\n ""databa..."
2,table,clinical_unit_ids,clinical_unit_ids,6,"CREATE TABLE ""clinical_unit_ids"" (\n""Select"" I..."
3,table,fact_table_init_status,fact_table_init_status,7,"CREATE TABLE ""fact_table_init_status"" (\n""tabl..."
4,table,PtAssessmentInterventions,PtAssessmentInterventions,9,"CREATE TABLE ""PtAssessmentInterventions"" (\n""i..."
5,table,PtLabResultInterventions,PtLabResultInterventions,79,"CREATE TABLE ""PtLabResultInterventions"" (\n""in..."
6,table,PtDemographicInterventions,PtDemographicInterventions,109,"CREATE TABLE ""PtDemographicInterventions"" (\n""..."
7,table,table_definitions,table_definitions,116,"CREATE TABLE ""table_definitions"" (\n""tableType..."
8,table,distinct_attributes,distinct_attributes,119,"CREATE TABLE ""distinct_attributes"" (\n""attribu..."
9,table,example_attribute_data,example_attribute_data,120,"CREATE TABLE ""example_attribute_data"" (\n""attr..."
10,table,final_mapping,final_mapping,2730,"CREATE TABLE ""final_mapping"" (\n""schemaVariabl..."
11,table,full_extract,full_extract,2734,"CREATE TABLE ""full_extract"" (\n""attributeId"" I..."

In [41]:
local_db.query_pd(
    "select * from final_mapping;"
    
)

,schemaVariable,interventionId,interventionLongLabel,priority,attributeId,attributeShortLabel,tableName
0,Gender,2631,Gender,0,11050,Gender,PtDemographic
1,BMI,2645,Body Mass Index,0,3723,BMI,PtDemographic
2,Weight,2110,Weight (admission),0,3588,Admit weight,PtDemographic
3,Weight,2110,Weight (admission),0,40554,Admit weight,PtDemographic
4,Weight,4615,Weight (Admission),0,1636,Weight,PtDemographic
...,...,...,...,...,...,...,...
138,Endotracheal tube,2316,ETT/Trache Cuff Inflated,0,6064,Cuff Inflated,PtAssessment
139,Endotracheal tube,25519,ETT/Trache Cuff Inflated,0,46466,Cuff Inflated,PtAssessment
140,Endotracheal tube,25519,ETT/Trache Cuff Inflated,0,46467,Pressure,PtAssessment
141,Endotracheal tube,70054,ETT/Trache Cuff Inflated,0,74755,Cuff Inflated,PtAssessment
142,Endotracheal tube,70612,ETT clamps present,0,75918,ETT clamps prese,PtAssessment

In [ ]:
df = local_db.query_pd(
    "select * from full_extract;"
    
)