### Postprocessing of data extracted by the Sniffer.

In [1]:
import sqlite3
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
# %matplotlib_inline

In [3]:
from application.utilities import LocalDatabaseWrapper

In [33]:
# project_name = "test_project"
project_name = "bmj_open_plus"
database_path = Path("./data")

In [34]:
local_db = LocalDatabaseWrapper(
            database_path / f"{project_name}.db"
        )

In [36]:
local_db.query_pd(
    "SELECT * from sqlite_schema where type='table'"
)

,type,name,tbl_name,rootpage,sql
0,table,schema,schema,2,"CREATE TABLE ""schema"" (\n""mapping_complete"" IN..."
1,table,info,info,3,"CREATE TABLE ""info"" (\n""name"" TEXT,\n ""databa..."
2,table,clinical_unit_ids,clinical_unit_ids,4,"CREATE TABLE ""clinical_unit_ids"" (\n""Select"" I..."
3,table,fact_table_init_status,fact_table_init_status,5,"CREATE TABLE ""fact_table_init_status"" (\n""tabl..."
4,table,PtAssessmentInterventions,PtAssessmentInterventions,7,"CREATE TABLE ""PtAssessmentInterventions"" (\n""i..."
5,table,PtLabResultInterventions,PtLabResultInterventions,77,"CREATE TABLE ""PtLabResultInterventions"" (\n""in..."
6,table,table_definitions,table_definitions,107,"CREATE TABLE ""table_definitions"" (\n""tableType..."
7,table,distinct_attributes,distinct_attributes,110,"CREATE TABLE ""distinct_attributes"" (\n""attribu..."
8,table,example_attribute_data,example_attribute_data,111,"CREATE TABLE ""example_attribute_data"" (\n""attr..."
9,table,final_mapping,final_mapping,3130,"CREATE TABLE ""final_mapping"" (\n""schemaVariabl..."

In [40]:
local_db.query_pd(
    "SELECT * from final_mapping"
)

,schemaVariable,interventionId,interventionLongLabel,priority,attributeId,attributeShortLabel,tableName
0,Pao2,734,pO2,0,10592,pO2,PtLabResult
1,Pao2,13963,pO2,0,37502,pO2,PtLabResult
2,Pao2,48950,Arterial pO2,0,16240,Value,PtLabResult
3,Pao2,48968,Arterial pO2 (TC),0,16240,Value,PtLabResult
4,Pao2,59328,Other pO2,0,16240,Value,PtLabResult
5,actual bicarbonate,720,HCO3-std,0,2880,Standard HCO3,PtLabResult
6,actual bicarbonate,770,Bicarbonate,0,6828,Bicarbonate,PtLabResult
7,Sodium,706,Sodium,0,1865,Sodium,PtLabResult
8,Sodium,726,Na,0,7868,Sodium,PtLabResult